name: sklearn-mlflow
channels:
  - defaults
dependencies:
  - python=3.8.6
  - pip:
    - mlflow==1.11.0
    - numpy=1.19.4
    - pandas=1.1.4
    - scikit-learn==0.23.2
    - scikit-plot==0.3.7
    - matplotlib==3.3.2
    - seaborn==0.11.0